export const Mapper: { [key: string]: string } = {
  likes: "like_count",
  dislikes: "dislike_count",
  comments: "comment_count",
  views: "view_count",
  videos: "channels.COUNT(videos)",
  "minimum views": "channels.MIN(videos.view_count)",
  "minimum likes": "channels.MIN(videos.like_count)",
  "minimum dislikes": "channels.MIN(videos.dislike_count)",
  "minimum comments": "channels.MIN(videos.comment_count)",
  "Skewness of likes distribution in comments": "SKEW(comments.likes)",
  "Comments per views": "comments_rate",
  "Average likes of comments": "MEAN(comments.likes)",
  "Minimum likes of comments": "MIN(comments.likes)",
  "Unique commentors": "NUM_UNIQUE(comments.username)",
  "Q scrore": "q_score",
  "Likes per views": "likes_rate",
  "Channel Skewness of likes distribution in comments":
    "channels.SKEW(comments.likes)",
  "Average comments per views": "channels.MEAN(videos.comments_rate)",
  "Channel Average likes of comments": "channels.MEAN(comments.likes)",
  "Channel Minimum likes of comments": "channels.MIN(comments.likes)",
  "Channel Unique commentors": "channels.NUM_UNIQUE(comments.username)",
  "Average Q scrore": "channels.MEAN(videos.q_score)",
  "Average Likes per views": "channels.MEAN(videos.likes_rate)",
};
